# Generated by Django 5.0.7 on 2024-07-15 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Silindi?'),
        ),
        migrations.AddField(
            model_name='post',
            name='live_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi?')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='Writer.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Beğenmeme',
                'verbose_name_plural': 'Beğenmemeler',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Son güncelleme tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi?')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Writer.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Beğeni',
                'verbose_name_plural': 'Beğeniler',
                'ordering': ['-create_date'],
            },
        ),
    ]
