# Generated by Django 5.0.7 on 2024-07-15 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0002_post_delete_date_post_is_delete_post_live_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Yorum')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Son Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi?')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-create_date'],
            },
        ),
    ]
