# Generated by Django 5.0.7 on 2024-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
