# Generated by Django 5.0.7 on 2024-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
